---
- name: Configure app clone server
  hosts: app-clone_servers
  remote_user: ubuntu
  become: yes # sudo

  tasks:
  # - name: Install nginx
  #   ansible.builtin.apt:
  #     name: nginx
  #     state: present
  # - name: Start and enable Nginx
  #   ansible.builtin.service:
  #     name: nginx
  #     state: started
  #     enabled: yes
  # - name: Copy Application Code
  #   ansible.builtin.copy:
  #     src: ../app/
  #     dest: /var/www/html


  # - name: Upload content to web site
  #   copy:
  #     content: yah hello from ansible
  #     dest: /var/www/html/index.html
      
  # install docker
  - name: Install required system packages for Docker
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: latest
      update_cache: true

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true
  
  - name: Create "app" directory on server
    ansible.builtin.file:
      path: /opt/a2-app/
      state: directory
      group: ubuntu
      mode: '774'
  - name: Upload App files
    ansible.posix.synchronize:
      src: ../app/
      dest: /opt/a2-app/v1/
      rsync_opts:
        - "--no-motd"
        - "--exclude=node_modules"
  #- name: Run application container
  #  shell: cd /opt/a2-app/v1; docker run --name foo_app --add-host host.docker.internal:host-gateway -e PORT=3001 -e DB_HOSTNAME=34.224.70.73 -e DB_PORT=5432 -e DB_USERNAME=pete -e DB_PASSWORD=devops -p 0.0.0.0:80:3001 -d mattcul/assignment2app:1.0.0
  - name: cd into folder
    shell: cd /opt/a2-app/v1/
  - name: Create & run application container
    community.docker.docker_container:
      name: "foo_app"
      image: "mattcul/assignment2app:1.0.0"
      env:
        PORT: "3001"
        DB_HOSTNAME: "{{ db_public_hostname }}"
        DB_PORT: "5432"
        DB_USERNAME: "pete"
        DB_PASSWORD: "devops"
      published_ports:
        - "0.0.0.0:80:3001"
      hostname:
        - "host.docker.internal:host-gateway"
      restart_policy: unless-stopped
      

  